title: "PostScript Language Guide"
description: "Comprehensive documentation for the PostScript programming language, covering operators, syntax, and practical usage examples"
# baseurl: "/postscript-guide"
url: "https://metanorma.github.io"

# Repository
repository: metanorma/postscript-guide

# Theme configuration
theme: just-the-docs
color_scheme: light

# Logo and favicon
logo: "/docs/assets/images/logo.svg"
favicon_ico: "/docs/assets/images/favicon.ico"

# AsciiDoc support
asciidoc: {}
asciidoctor:
  attributes:
    idprefix: ''
    idseparator: '-'
    source-highlighter: rouge
    icons: font
    experimental: true
    sectanchors: true
    linkattrs: true
    sectnums: true
    toc: left
    toclevels: 3

# Search configuration
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# Navigation
nav_sort: case_insensitive
nav_fold: true

# External links
aux_links:
  "Source":
    - "https://github.com/metanorma/postscript-guide"
  "Report Issues":
    - "https://github.com/metanorma/postscript-guide/issues"
  "Adobe PostScript Language Reference Manual":
    - "https://www.adobe.com/jp/print/postscript/pdfs/PLRM.pdf"

aux_links_new_tab: true

# Back to top
back_to_top: true
back_to_top_text: "Back to top"

# Heading anchors
heading_anchors: true

# Footer
footer_content: "Copyright &copy; 2025 Metanorma. PostScript is a trademark of Adobe. Distributed under the <a href=\"https://github.com/metanorma/postscript-guide/blob/main/LICENSE\">MIT License</a>."

# Collections
collections:
  commands:
    output: true
    permalink: /commands/:path/
  pages:
    output: true
    permalink: /:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  # - scope:
  #     path: "docs"
  #   values:
  #     layout: default

# Plugins
plugins:
  - jekyll-asciidoc
  - jekyll-seo-tag

# Markdown settings (for any markdown files)
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .bundle
  - README.md
  - LICENSE
  - .git
  - .gitignore

# # Include
# include:
#   - .
#   - commands
#   - examples
#   - levels

permalink: pretty
includes_dir: 'docs'
