---
layout: default
title: arc
parent: Path Construction
grand_parent: Command Reference
nav_order: 7
---

== arc

Appends a counterclockwise circular arc to the current path.

=== Syntax

----
x y r ang1 ang2 arc → -
----

=== Stack Effects

.Before
[cols="1,3"]
|===
| Level | Object

| 4
| `ang2` (number - ending angle in degrees)

| 3
| `ang1` (number - starting angle in degrees)

| 2
| `r` (number - radius)

| 1
| `y` (number - center y-coordinate)

| 0
| `x` (number - center x-coordinate)
|===

.After
[cols="1,3"]
|===
| Level | Object

| (empty)
| Stack cleared of operands
|===

=== Description

link:arc.adoc[`arc`] appends a counterclockwise arc of a circle to the current path. The arc has (x, y) as center, r as radius, ang1 as the angle from (x, y) to the first endpoint, and ang2 as the angle from (x, y) to the second endpoint.

Angles are measured in degrees counterclockwise from the positive x-axis of the current user coordinate system.

If there is a current point, link:arc.adoc[`arc`] includes a straight line segment from the current point to the first endpoint of the arc, then adds the arc into the current path. If the current path is empty, link:arc.adoc[`arc`] does not produce the initial straight line segment. In any event, the second endpoint of the arc becomes the new current point.

The curve produced is circular in user space. If user space is scaled non-uniformly (differently in x and y), link:arc.adoc[`arc`] will produce elliptical curves in device space.

=== PostScript Level

*Level 1* and later

=== Examples

.Drawing a circle
[source,postscript]
----
newpath
200 200 50 0 360 arc
closepath
fill
----

.Drawing a semicircle
[source,postscript]
----
newpath
200 200 75 0 180 arc
closepath
stroke
----

.Creating a pie slice
[source,postscript]
----
newpath
200 200 moveto           % Move to center
200 200 100 0 45 arc     % Draw arc from 0° to 45°
closepath                % Line back to center
fill
----

.Drawing partial circles
[source,postscript]
----
newpath
150 150 50 45 135 arc    % Upper-right quadrant
stroke

newpath
150 150 50 225 315 arc   % Lower-left quadrant
stroke
----

=== Common Use Cases

==== Drawing Circular Shapes

[source,postscript]
----
/drawCircle {
  % x y radius
  /r exch def
  /y exch def
  /x exch def
  newpath
  x y r 0 360 arc
  closepath
} def

200 200 50 drawCircle
fill
----

==== Creating Rounded Corners

[source,postscript]
----
/roundedRect {
  % x y width height radius
  /r exch def
  /h exch def
  /w exch def
  /y exch def
  /x exch def

  newpath
  x r add y moveto
  x w add r sub y r 0 90 arc       % Bottom-right
  x w add y h add r sub r 90 180 arc   % Top-right
  x r add y h add r 180 270 arc        % Top-left
  x y r add r 270 360 arc              % Bottom-left
  closepath
} def

100 100 200 150 20 roundedRect
stroke
----

==== Drawing Gauges and Dials

[source,postscript]
----
/drawGauge {
  % cx cy radius startAngle endAngle value
  /val exch def
  /endAng exch def
  /startAng exch def
  /r exch def
  /cy exch def
  /cx exch def

  % Draw arc background
  newpath
  cx cy r startAng endAng arc
  0.7 setgray
  5 setlinewidth
  stroke

  % Draw value indicator
  newpath
  cx cy r startAng
  startAng endAng startAng sub val mul add arc
  1 0 0 setrgbcolor
  stroke
} def

200 200 80 135 45 0.75 drawGauge
----

=== Common Pitfalls

WARNING: *Angle Units* - Angles are in **degrees**, not radians. A full circle is 360°, not 2π.

[source,postscript]
----
200 200 50 0 6.28 arc   % Wrong! Only draws ~6° of arc
200 200 50 0 360 arc    % Correct: full circle
----

WARNING: *Counterclockwise Direction* - link:arc.adoc[`arc`] always draws counterclockwise. For clockwise arcs, use xref:arcn.adoc[`arcn`].

[source,postscript]
----
% For clockwise 90° arc from 0° to -90°:
200 200 50 0 -90 arc    % Wrong! Draws 270° counterclockwise
200 200 50 0 -90 arcn   % Correct: 90° clockwise
----

WARNING: *Non-uniform Scaling* - If the CTM has non-uniform scaling, arcs become elliptical.

[source,postscript]
----
2 1 scale               % Scale x by 2, y by 1
100 100 50 0 360 arc    % Produces an ellipse, not a circle
----

TIP: *Connecting Line* - If a current point exists, link:arc.adoc[`arc`] adds a connecting line to the arc's start. Use xref:moveto.adoc[`moveto`] to the start point to avoid this.

=== Implementation Notes

* Arcs are internally represented as one or more Bézier cubic curves
* The conversion is accurate enough for faithful arc rendering
* Programs using `pathforall` will see xref:curveto.adoc[`curveto`] segments
* Angles wrap around: 370° is equivalent to 10°
* Negative angles are valid: -90° equals 270°
* Zero radius creates a point (degenerate arc)

=== Error Conditions

[cols="1,3"]
|===
| Error | Condition

| [`limitcheck`]
| Path becomes too complex for implementation

| [`stackunderflow`]
| Fewer than 5 operands on stack

| [`typecheck`]
| Any operand is not a number
|===

=== Performance Considerations

* Arcs are efficient primitives
* Large arcs (many degrees) may use multiple curve segments
* Multiple small arcs may be slower than one large arc
* Circular arcs in user space may be expensive if transformed to complex ellipses

=== See Also

* xref:arcn.adoc[`arcn`] - Clockwise arc
* xref:arct.adoc[`arct`] - Arc defined by tangent lines
* xref:arcto.adoc[`arcto`] - Like arct but returns tangent points
* xref:curveto.adoc[`curveto`] - Bézier cubic curve
* xref:moveto.adoc[`moveto`] - Set current point
* xref:closepath.adoc[`closepath`] - Close current subpath