---
layout: default
title: setgray
parent: Command Reference
nav_order: 3
---

== setgray

Sets the current gray level for painting operations.

=== Syntax

----
num setgray → –
----

=== Stack Effects

.Before
[cols="1,3"]
|===
| Level | Object

| 0
| `num` (0.0 = black to 1.0 = white)
|===

.After
[cols="1,3"]
|===
| Level | Object

| (empty)
| Color space set to DeviceGray, color set to num
|===

=== Description

link:/commands/references/setgray/[`setgray`] sets the color space to DeviceGray and sets the current color to a gray shade corresponding to _num_.

* **0** = black
* **1** = white
* **0.5** = 50% gray
* Intermediate values = intermediate grays

This establishes the color for subsequent painting operations (lines, fills, text).

Values outside 0-1 are clamped to nearest legal value (no error).

=== PostScript Level

*Level 1* and later

=== Examples

.Basic gray levels
[source,postscript]
----
0 setgray     % Black
1 setgray     % White
0.5 setgray   % 50% gray
----

.Drawing with different grays
[source,postscript]
----
0 setgray
0 0 moveto 100 0 lineto stroke  % Black line

0.5 setgray
0 10 moveto 100 10 lineto stroke  % Gray line

1 setgray
0 20 moveto 100 20 lineto stroke  % White line
----

.Grayscale fills
[source,postscript]
----
0.2 setgray
0 0 50 50 rectfill  % Dark gray rectangle

0.8 setgray
60 0 50 50 rectfill  % Light gray rectangle
----

=== Common Use Cases

==== Black and White Graphics

[source,postscript]
----
/drawBW {
  gsave
    0 setgray  % Black
    drawOutline stroke
    1 setgray  % White
    drawInterior fill
  grestore
} def
----

==== Grayscale Gradients

[source,postscript]
----
0 0.01 1 {
  dup setgray
  currentpoint translate
  drawBand
} for
----

==== Text Rendering

[source,postscript]
----
0 setgray
/Helvetica findfont 12 scalefont setfont
100 100 moveto (Black text) show

0.5 setgray
100 80 moveto (Gray text) show
----

=== Common Pitfalls

WARNING: *Changes Color Space* - link:/commands/references/setgray/[`setgray`] changes color space to DeviceGray.

[source,postscript]
----
1 0 0 setrgbcolor  % Red (DeviceRGB)
0.5 setgray        % Gray (DeviceGray - RGB lost!)
----

WARNING: *Values Clamped* - Out-of-range values are adjusted, not rejected.

[source,postscript]
----
1.5 setgray   % Becomes 1.0 (white)
-0.5 setgray  % Becomes 0.0 (black)
----

TIP: *Use for Monochrome* - Most efficient color operation for monochrome output.

=== Error Conditions

[cols="1,3"]
|===
| Error | Condition

| [`stackunderflow`]
| No operand on stack

| [`typecheck`]
| Operand not a number

| [`undefined`]
| Operator disabled in certain contexts
|===

=== Implementation Notes

* Very fast operation
* Most efficient color setting (single value)
* Widely supported on all devices
* Default color space for many operations

=== See Also

* link:/commands/references/setrgbcolor/[`setrgbcolor`] - Set RGB color
* link:/commands/references/setcmykcolor/[`setcmykcolor`] - Set CMYK color (Level 2)
* link:/commands/references/sethsbcolor/[`sethsbcolor`] - Set HSB color
* link:/commands/references/currentgray/[`currentgray`] - Get current gray value
* Color operations (to be documented) - Advanced color spaces