---
layout: default
title: gstate
parent: Graphics State
grand_parent: Command Reference
nav_order: 10
---

== gstate

Creates a graphics state object.

=== Syntax

----
– gstate → gstate
----

=== Stack Effects

.Before
[cols="1,3"]
|===
| Level | Object

| (empty)
| –
|===

.After
[cols="1,3"]
|===
| Level | Object

| 0
| `gstate` (graphics state object)
|===

=== Description

[`gstate`](gstate.adoc) creates a new gstate (graphics state) object and pushes it on the operand stack. Its initial value is a copy of the current graphics state, including all graphics parameters such as:

* Current transformation matrix (CTM)
* Color space and color
* Line width, cap, join, and dash pattern
* Miter limit
* Current font
* Clipping path
* And all other graphics state parameters

This operator consumes VM; it is the only graphics state operator that does. The gstate is allocated in either local or global VM according to the current VM allocation mode.

The gstate object can later be used with [`setgstate`](setgstate.adoc) to restore the graphics state to the captured values, or with [`currentgstate`](currentgstate.adoc) to update the saved state.

=== PostScript Level

*Level 2* and later

=== Examples

.Creating and using gstate
[source,postscript]
----
gstate                  % Create gstate object
/MyState exch def       % Save it

% Modify graphics state
2 2 scale
0.5 setgray
3 setlinewidth

% Restore previous state
MyState setgstate
----

.Saving multiple states
[source,postscript]
----
% Save initial state
gstate /InitialState exch def

% Make some changes
1 0 0 setrgbcolor
/Helvetica findfont 12 scalefont setfont

% Save modified state
gstate /ModifiedState exch def

% Switch between states
InitialState setgstate   % Back to initial
ModifiedState setgstate  % To modified
----

.State management in procedures
[source,postscript]
----
/DrawWithState {
  % Create state snapshot
  gstate

  % Draw with custom settings
  0.5 setlinewidth
  1 0 0 setrgbcolor
  drawShape

  % Restore state
  setgstate
} def
----

=== Common Use Cases

==== Preserving Graphics State

[source,postscript]
----
% Save entire state for later
gstate /SavedState exch def

% Do complex operations
modifyManyParameters
drawComplexGraphic

% Restore everything at once
SavedState setgstate
----

==== Multiple State Snapshots

[source,postscript]
----
/StateLibrary 10 dict def

% Save different states
gstate StateLibrary /NormalState 3 -1 roll put
1 0 0 setrgbcolor
gstate StateLibrary /RedState 3 -1 roll put
0 1 0 setrgbcolor
gstate StateLibrary /GreenState 3 -1 roll put

% Use saved states
StateLibrary /RedState get setgstate
StateLibrary /NormalState get setgstate
----

==== State Templates

[source,postscript]
----
% Create template states
/HeaderState {
  /Helvetica-Bold findfont 18 scalefont setfont
  0 setgray
  2 setlinewidth
  gstate
} def

/BodyState {
  /Times-Roman findfont 10 scalefont setfont
  0 setgray
  0.5 setlinewidth
  gstate
} def
----

=== Common Pitfalls

WARNING: *VM Consumption* - [`gstate`](gstate.adoc) allocates memory; excessive use can exhaust VM.

[source,postscript]
----
% Bad: Creating gstate in loop
1 1 1000 {
  gstate /temp exch def  % VM grows!
} for
----

WARNING: *Global VM Restrictions* - Creating gstate in global VM when graphics state contains local VM objects causes error.

[source,postscript]
----
true setglobal
/LocalFont /Helvetica findfont def  % Local VM
gstate  % Error: invalidaccess
----

WARNING: *Not a Substitute for gsave* - Use [`gsave`](gsave.adoc)/[`grestore`](grestore.adoc) for simple state save/restore.

[source,postscript]
----
% Inefficient
gstate /temp exch def
drawShape
temp setgstate

% Better
gsave
drawShape
grestore
----

TIP: *Use for Templates* - [`gstate`](gstate.adoc) is ideal for creating reusable state configurations.

=== Error Conditions

[cols="1,3"]
|===
| Error | Condition

| [`invalidaccess`]
| gstate in global VM but current state contains local VM objects

| [`stackoverflow`]
| No room on operand stack

| [`VMerror`]
| Insufficient VM to allocate gstate object
|===

=== Implementation Notes

* Only graphics state operator that consumes VM
* Allocated in local or global VM based on current allocation mode
* Contains complete copy of graphics state
* Can be used repeatedly with [`setgstate`](setgstate.adoc)
* More expensive than [`gsave`](gsave.adoc) but more flexible
* Best used for state templates, not simple save/restore

=== Graphics State Components

The gstate object captures all of the following:

* Transformation matrix (CTM)
* Color space and color values
* Line parameters (width, cap, join, dash, miter limit)
* Current font
* Current path (not saved - always empty)
* Clipping path
* Flatness tolerance
* Stroke adjustment
* Halftone, transfer function, black generation
* Rendering intent (Level 3)

=== See Also

* xref:setgstate.adoc[`setgstate`] - Replace graphics state from gstate
* xref:currentgstate.adoc[`currentgstate`] - Update gstate with current state
* xref:gsave.adoc[`gsave`] - Save graphics state on stack
* xref:grestore.adoc[`grestore`] - Restore graphics state from stack
* xref:grestoreall.adoc[`grestoreall`] - Restore all saved states
