name: links

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  link_checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Build site
      env:
        JEKYLL_ENV: production
      run: bundle exec jekyll build --trace

    - name: Restore lychee cache
      uses: actions/cache@v4
      with:
        path: .lycheecache
        key: cache-lychee-${{ github.sha }}
        restore-keys: cache-lychee-

    - name: Check if site was built
      run: |
        if [ ! -d "_site" ]; then
          echo "Error: _site directory not created"
          exit 1
        fi
        echo "Site built successfully"
        ls -la _site/

    - name: Link Checker (Built Site)
      uses: lycheeverse/lychee-action@v2
      with:
        # Check the built HTML site for rendered links
        args: >-
          --verbose
          --no-progress
          --config lychee.toml
          --format markdown
          --output link-check-results.md
          --base '_site'
          --cache
          --max-cache-age 1d
          --root-dir /
          '_site/**/*.html'
        fail: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Link Checker (Source AsciiDoc)
      uses: lycheeverse/lychee-action@v2
      with:
        # Also check source AsciiDoc files for xref links
        args: >-
          --verbose
          --no-progress
          --config lychee.toml
          --format markdown
          --output link-check-source.md
          'docs/**/*.adoc'
        fail: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Upload link check results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: link-check-results
        path: |
          link-check-results.md
          link-check-source.md
        retention-days: 30

    - name: Comment PR with results
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          let comment = '## 🔗 Link Check Failed\n\n';

          if (fs.existsSync('link-check-results.md')) {
            const results = fs.readFileSync('link-check-results.md', 'utf8');
            comment += '### Built Site Results\n\n' + results + '\n\n';
          }

          if (fs.existsSync('link-check-source.md')) {
            const source = fs.readFileSync('link-check-source.md', 'utf8');
            comment += '### Source Files Results\n\n' + source;
          }

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });